script:
  - "make $TEST_SUITE"

language: node_js

node_js:
  - "0.10"
  - "0.12"

env:
  - TEST_SUITE=test
  - TEST_SUITE=test-harmony

matrix:
  fast_finish: true
  include:
    - node_js: "0.12"
      env:
        - TEST_SUITE=test-harmony
        - COVERAGE=true
  allow_failures:
    - env:
        - TEST_SUITE=test-harmony
        - COVERAGE=true

branches:
  only:
    - master
    - dev

sudo: false
